---
# tasks file for OULibraries.java

- name: Create downloads directory
  file:
    path: "/tmp/downloads"
    state: directory
    mode: 0655
    owner: root
    group: wheel

- name: Create Apache Project installation directory
  file:
    path: /opt/apache/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Calculate closest apache mirror
  shell: >
   curl -s 'https://www.apache.org/dyn/closer.cgi?as_json=1' \
   | python -c "import sys, json; print json.load(sys.stdin)['preferred']"
  register: get_mirror

- set_fact: 
    java_apache_mirror:  "{{ get_mirror.stdout }}"

- name: Download Apache Project java tools
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - url: "{{ java_apache_mirror }}/maven/maven-3/{{java_maven_version}}/binaries/apache-maven-{{java_maven_version}}-bin.tar.gz"
      dest: "/tmp/downloads/apache-maven-{{java_maven_version}}-bin.tar.gz"

- name: Install Apache Project java tools
  unarchive:
#    remote_src: yes
    copy: no
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: "/tmp/downloads/apache-maven-{{java_maven_version}}-bin.tar.gz"
      dest: /opt/apache

- name: Build standard links for Apache Java tools
  file:
    state: link
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
     - src: /opt/apache/apache-maven-{{java_maven_version}}
       dest: /opt/apache/maven

- name: Ensure /etc/profile.d/java-tools.sh exists
  file:
    path: /etc/profile.d/java-tools.sh
    state: touch
    mode: 0644
    owner: root
    group: wheel

- name: Add Java tools to path
  lineinfile:
    state: present
    dest: /etc/profile.d/java-tools.sh
    line: "export PATH=/opt/apache/maven/bin:$PATH"
