# Oracle Java JDK is required by Djatoka, can't use OpenJDK
- name: get JDK from Oracle
  get_url:
    url: "http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jdk-8u102-linux-x64.rpm"
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest: "/tmp/downloads/jdk-8u102-linux-x64.rpm"

- name: Install Oracle JDK RPM
  yum:
    name: "/tmp/downloads/jdk-8u102-linux-x64.rpm"
    state: present
